baseURL = 'https://ageoftitus.com/'
languageCode = 'en-us'
title = 'Age of Titus - Where Noobs play'

theme = 'cyberscape'

# Add any links to things in /content/ here
[[menu.main]]
name = "Strategies"
url = "/strategies/"
weight = 1

[[menu.main]]
name = "resources"
url = "/resources/"
weight = 2

# Enable this for Tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true
