baseURL = 'https://ageoftitus.com/'
languageCode = 'en-us'
title = 'Age of Titus'
copyright = "2024 Titus Tech Gaming"
theme = 'diary'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[params]
subtitle = "Titus Tech Gaming"
enableGiscus = true
enableOpenGraph = true
title = "Age of Titus" # will set 'og:site_name'
description = "Titus Tech Gaming"  # will set 'og:description'

[params.social]
youtube = "https://www.youtube.com/titustechgaming"
twitch = "https://www.twitch.tv/titustechgaming"

[taxonomies]
   tag = "tags"
   category = "categories"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data-repo="christitustech/ageoftitus"
    data-repo-id="R_kgDOM7Hpmg"
    data-category="Announcements"
    data-category-id="DIC_kwDOM7Hpms4Cjaql"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="dark"
    data-lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/"
name = "Strategies"
weight = 2
[[menu.main]]
url = "/games/"
name = "Games"
weight = 1
